markdown: kramdown
highlighter: pygments
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

google_analytics_id: UA-46880695-1

organization_url: https://github.com/frida
repository: https://github.com/frida/frida

timezone: Europe/Oslo

collections:
  docs:
    output: true

name: Frida • A world-class dynamic instrumentation framework
description: Inject JavaScript to explore native apps on Windows, Mac, Linux, iOS and Android
url: http://www.frida.re

twitter:
  username: fridadotre

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-gist
