highlight: pygments
relative_permalinks: false
google_analytics_id: UA-46880695-1
permalink: /news/:year/:month/:day/:title/
excerpt_separator: noifniof3nioaniof3nioafafinoafnoif
repository: https://github.com/frida
